const data = [
  {
    No: "1",
    iOS_page: "1",
    AOS_page: "1",
    class: "primary",
    typeText: "필수",
    title: "촬영하고자 하는 소재 선택하기",
    description: "어떻게 촬영하면 좋을지 가이드를 받아보세요.",
  },
  {
    No: "2",
    iOS_page: "1",
    AOS_page: "2",
    class: "primary",
    typeText: "필수",
    title: "촬영하기",
    description: "촬영화면에 대해 알아보세요.",
  },
  {
    No: "3",
    iOS_page: "1",
    AOS_page: "3",
    class: "primary",
    typeText: "필수",
    title: "클립 길이 조절하기",
    description: " 클립 길이 조절하는 방법에 대해 알아보세요.",
  },
  {
    No: "4",
    iOS_page: "1",
    AOS_page: "4",
    class: "primary",
    typeText: "필수",
    title: "클립 편집 추가 기능 알아보기",
    description: "삭제, 음량 조절, 복사 기능에 대해 알아보세요.",
  },
  {
    No: "5",
    iOS_page: "1",
    AOS_page: "5",
    class: "primary",
    typeText: "필수",
    title: "자막 추가하기",
    description: "클립에 자막 추가하는 방법을 알아보세요.",
  },
  {
    No: "6",
    iOS_page: "1",
    AOS_page: "6",
    class: "primary",
    typeText: "필수",
    title: "자막 스타일 변경하기",
    description: "자막 스타일 변경하는 방법에 대해 알아보세요.",
  },
  {
    No: "7",
    iOS_page: "1",
    AOS_page: "7",
    class: "primary",
    typeText: "필수",
    title: "자막 여러 개 넣기",
    description: "한 클립에 여러 개의 자막을 넣어보세요.",
  },
  {
    No: "8",
    iOS_page: "1",
    AOS_page: "8",
    class: "primary",
    typeText: "필수",
    title: "자막 여러 개 넣기",
    description: "한 클립에 여러 개의 자막을 넣어보세요.",
  },
  {
    No: "9",
    iOS_page: "1",
    AOS_page: "9",
    class: "primary",
    typeText: "필수",
    title: "이미지 추가하기",
    description: "화면 위에 이미지를 추가해보세요.",
  },
  {
    No: "10",
    iOS_page: "1",
    AOS_page: "10",
    class: "primary",
    typeText: "필수",
    title: "음악 추가하기",
    description: "음악을 추가하는 방법에 대해 알아보세요.",
  },
  {
    No: "11",
    iOS_page: "1",
    AOS_page: "11",
    class: "primary",
    typeText: "필수",
    title: "효과음 추가하기",
    description: "효과음을 추가하는 방법에 대해 알아보세요.",
  },
  {
    No: "12",
    iOS_page: "1",
    AOS_page: "12",
    class: "primary",
    typeText: "필수",
    title: "더빙하기",
    description: "최종적으로 녹음하는 방법에 대해 알아보세요.",
  },

];

export default data;
